config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/locations/mylocations', to: 'locations#mylocations'
  get '/contracts/consumer', to: 'contracts#consumer'
  get '/contracts/owner', to: 'contracts#owner'

  root "application#aboutus"

  get '/users/email_confirmation', to: 'users#email_confirmation'

  resources :users
  resources :contracts
  resources :locations

  resources :locations, only: [:show] do
    # nested resource for contracts
    resources :contracts, only: [:new, :show, :index]
  end
#for new, look the nested routes up and plug into <%= link_to "add contract" new_catagory_item_path(c) %>
#

  get '/feedbacks/thankyou', to: 'feedbacks#thankyou'
  resources :feedbacks
  
  get '/aboutus', to: 'application#aboutus'
  
  get '/logout', to: 'sessions#logout'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#login_post'

  get '/signup', to: 'sessions#signup'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  #get ‘auth/failure’, to: redirect(‘/’)
  
end

app/models/contract.rb
class Contract < ApplicationRecord
    
    belongs_to :owner, class_name: 'User'
    belongs_to :consumer, class_name: 'User'

    belongs_to :location

    validates :owner_id, :consumer_id, :location_id, :capacity, :term, :rate, presence: true
    validates :owner_id, :consumer_id, :location_id, :capacity, :term, :rate, numericality: { only_integer: true }
    validates :status, length: { is: 8 }
    validates :status,
                    inclusion: {
                        in: [
                        'Proposed',
                        'Accepted',
                        'Declined'
                        ],
                        message: "Please select Accepted or Declined"
                    }

    #scope method for kWh* term of contract for total kWh fascilitated                    
    scope :Proposed, -> { where(status: "Proposed") }
    scope :Accepted, -> { where(status: "Accepted") }
    scope :Declined, -> { where(status: "Declined") }


    def end_date(c)
        finish = c.created_at + (c.term*365).day
    end


end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

    def new
        @contract=Contract.new
        @location=Location.find_by(id: session[:last_location])
    end

    def show
        if valid_contract && authorized_contract
            session[:last_contract] = @contract.id    
        else
            flash[:error] = "You are not authorized to see this contract"
            redirect_to root_path
        end
    end

    def create
        @contract = Contract.create(contract_params) do |c|
            c.owner_id = Location.find_by(id: session[:last_location]).owner.id
            c.consumer_id = session[:user_id]
            c.location_id = Location.find_by(id: session[:last_location]).id
            c.status = "Proposed"
            end
        if @contract.valid?
            @user = @contract.owner
            @location = @contract.location
            UserMailer.with(user: @user, location: @location).contract_recieved_email.deliver_later
            redirect_to contract_path(@contract)
        else
            @location=Location.find_by(id: session[:last_location])
            render new_contract_path
        end       
    end

    def consumer
        @contracts = Contract.where(consumer_id: session[:user_id]).order('contracts.updated_at DESC')
    end

    def owner
        @contracts = Contract.where(owner_id: session[:user_id]).order('contracts.updated_at DESC')
    end

    def update
        if valid_contract && owner_contract && valid_origin
            @contract.update(update_params)
            if @contract.valid?
                @owner = @contract.owner
                @consumer = @contract.consumer
                @location = @contract.location
                #this will also email both even if rejected
                if @contract.status == "Accepted"
                    UserMailer.with(owner: @owner, consumer: @consumer, location: @location, contract: @contract).contract_accepted_email_owner.deliver_later
                    UserMailer.with(owner: @owner, consumer: @consumer, location: @location, contract: @contract).contract_accepted_email_consumer.deliver_later
                elsif @contract.status == "Declined"
                    UserMailer.with(consumer: @consumer, location: @location, contract: @contract).contract_declined_email_consumer.deliver_later
                end
                redirect_to contract_path(@contract)
            else
                @contract.status = "Proposed"
                render "contracts/show"
            end
        end
    end

    def index
        if params[:location_id]
          @contracts = Location.find(params[:location_id]).contracts
          @location = Location.find(params[:location_id])
        else
          flash[:error] = "You are not authorized to see this"
          redirect_to root_path
        end
      end

    private

    def contract_params
        params.require(:contract).permit(:capacity, :term, :rate)
    end
    
    def update_params
        params.require(:contract).permit(:status)
    end

    def valid_contract
        if !@contract=Contract.find_by(id: params[:id]) 
            false
        else
            true
        end
    end

    def authorized_contract
        @contract.owner_id == session[:user_id] || @contract.consumer_id == session[:user_id]
    end

    def owner_contract
        @contract.owner_id == session[:user_id]
    end

    def valid_origin
        params[:id].to_i == session[:last_contract]
    end

end

app/helpers/contract_helper.rb
module ContractHelper

    def status_helper
        [
          ['Select this option for new proposals', 'Proposed'],
          ['Accepted', 'Accepted'],
          ['Declined', 'Declined'],
        ]
    end

end

app/views/contracts/_contracts.html.erb
<% if @contracts.length == 0 %>
    <br>
    <div class="center-font">You don't have any contracts to view.</div>
<% else %>

    <body>
        <div class="container">
            <div class="row">

                <% @contracts.each do |c| %>
                    <div class="card">
                        <div class="card-header-contract">
                            <h2><%= c.status %></h2><br>
                        </div>

                        <div class="card-body">
                            <p>Submitted: <%= c.created_at.strftime('%B %-d, %Y') %><br>
                            End date: <%= c.end_date(c).strftime('%B %-d, %Y') %><br>
                            Location Owner: <%= c.owner.name %><br>
                            Consumer Name: <%= c.consumer.name %><br>
                            Location Name: <%= c.location.name %></p><br>

                            
                            <p>Contracted Amount: <%= c.capacity %> kWh<br>
                            Contracted Term: <%= c.term %> years<br>
                            Contracted Repayment Rate: <%= c.rate %>%</p><br>
                        
                            <% if @location %>
                                <a href="<%= location_contract_path(@location, c) %>" class="btn-contract">See Details</a>
                            <% else %>
                                <a href="<%= contract_path(c) %>" class="btn-contract">See Details</a>
                            <% end %>

                        </div>
                    </div>   


                <% end %>
            </div>
        </div>
    </body>
<% end %>

app/views/contracts/_response.html.erb
        <h4>Please read carefully before proceeding, you have three options:</h4>
        A) If you decide to negotiate with the consumer, please contact them using their email, decline this offer & have them resubmit a new offer based on agreed terms.<br>
        <ol>
        <li>Consumers Email: <%= @contract.consumer.email %></li>
        <li>Next, Decline.  This action cannot be undone.</li>
        </ol>
        B) You may decline and not respond to the offer by selecting decline.<br><br>

        C) You may accept the offer.  This is not a legally binding contract, please email the consumer to contract the agreement based on the offer terms.<br><br>

            <%= form_with model: @contract do |f| %>

                <% if @contract.errors.any? %>
                    <div id="error_explanation">
                        <h2>
                        <%= pluralize(@contract.errors.count, "error") %>
                        prohibited this contract from being submitted:
                        </h2>
                        <ul>
                        <% @contract.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <% end %>
                        </ul>
                    </div>
                <% end %>

                <%= f.label :status %>
                <%= f.select :status, ["Please Select an Option", "Accepted", "Declined"] %><br><br>
                <br>
                <%= f.submit "Click to Finalize"%>
            <% end %>

app/views/contracts/_summary.html.erb
    Contract Status: <%= @contract.status %><br>
    Submitted: <%= @contract.created_at.strftime('%B %-d, %Y') %><br>
    End date: <%= @contract.end_date(@contract).strftime('%B %-d, %Y') %><br>
    Location Owner: <%= @contract.owner.name %><br>
    Consumer Name: <%= @contract.consumer.name %><br>
    Location Name: <%= @contract.location.name %><br>
    Contracted Amount: <%= @contract.capacity %> kWh<br>
    Contracted Term: <%= @contract.term %> years<br>
    Contracted Repayment Rate: <%= @contract.rate %>%<br></p>

app/views/contracts/consumer.html.erb
<%= render 'contracts' %>

app/views/contracts/index.html.erb
<%= render 'contracts' %>

<%= link_to "click to create a new contract for this location", new_location_contract_path(@location) %>

app/views/contracts/new.html.erb
<h2>The Owner has up to <%=@location.annual_capacity-@location.contracts.Accepted.sum(:capacity) %> kWh per year available</h2>
<%= form_with model: @contract do |f| %>

<% if @contract.errors.any? %>
        <div id="error_explanation">
            <h2>
            <%= pluralize(@contract.errors.count, "error") %>
            prohibited this contract from being submitted:
            </h2>
            <ul>
            <% @contract.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>



    <%= f.label :annual_capacity_requested_in_kwh %>
    <%= f.text_field :capacity %>
    <br>
    <%= f.label :term_in_full_years %>
    <%= f.text_field :term %>
    <br>
    <%= f.label :percentage_repayment_rate %>
    <%= f.text_field :rate %><br>
    *you plan to pay $xx back to the owner for each $100 recieved in bill credits
    <br>
    <%= f.submit "Submit proposal to owner"%>
<% end %>

app/views/contracts/owner.html.erb
<%= render 'contracts' %>

app/views/contracts/show.html.erb
<h1>Contract Details</h1>


<% if @contract.status == "Proposed" && @contract.created_at == @contract.updated_at %>
    <p style="color:gray">
    <%= render 'summary' %>
    <% if @contract.owner.id == current_user%>
        <%= render 'response' %>
    <% end %>
<% elsif @contract.status == "Accepted" %>
    <p style="color:blue">
    <%= render 'summary' %>
<% elsif @contract.status == "Declined" %>
    <p style="color:red">
    <%= render 'summary' %>
<% end %>