config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/locations/mylocations', to: 'locations#mylocations'
  get '/contracts/consumer', to: 'contracts#consumer'
  get '/contracts/owner', to: 'contracts#owner'

  root "application#aboutus"

  get '/users/email_confirmation', to: 'users#email_confirmation'

  resources :users
  resources :contracts
  resources :locations

  resources :locations, only: [:show] do
    # nested resource for contracts
    resources :contracts, only: [:new, :show, :index]
  end
#for new, look the nested routes up and plug into <%= link_to "add contract" new_catagory_item_path(c) %>
#

  get '/feedbacks/thankyou', to: 'feedbacks#thankyou'
  resources :feedbacks
  
  get '/aboutus', to: 'application#aboutus'
  
  get '/logout', to: 'sessions#logout'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#login_post'

  get '/signup', to: 'sessions#signup'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  #get ‘auth/failure’, to: redirect(‘/’)
  
end

app/models/location.rb
class Location < ApplicationRecord

    belongs_to :owner, class_name: 'User'
    has_many :contracts

    validates :name, :owner_id, :utility, :zone, :meter_type, :state, :country, :annual_capacity, :status, presence: true
    validates :annual_capacity, numericality: { only_integer: true }
    validates :state, length: { is: 2 }

    scope :state, -> (state) { where("state = ?", state) }


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    def mylocations
        @user = User.find_by(id: session[:user_id])
        @locations = @user.owned_assets
    end

    def new
        @location = Location.new
    end

    def create
        @location = Location.create(location_params) do |l|
            l.owner_id = session[:user_id]
        end

        if @location.save
            redirect_to location_path(@location)
        else
            render "locations/new"
        end
    end

    def show
        @location = Location.find_by(id: params[:id])
        session[:last_location] = @location.id
    end

    def edit
        edit_authorized
        session[:last_location] = @location.id
    end

    def update
        edit_authorized
        if @location.update(location_params)
            redirect_to location_path(@location)
        else
            render "locations/edit"
        end
    end

    def index
        @locations = Location.all
    end

    private

    def location_params
        params.require(:location).permit(:name, :utility, :zone, :meter_type, :state, :country, :annual_capacity, :status)
    end

    def edit_authorized
        if @location = Location.find_by(id: params[:id])
            if @location.id != session[:last_location]
                flash[:error] = "You are not authorized to edit this location"
                redirect_to root_path
            end
        else
            flash[:error] = "You are not authorized to edit this location"
            redirect_to root_path
        end
    end

end

app/helpers/location_helper.rb
module LocationHelper

    def us_states
        [
          ['Please Select a State', ''],
          ['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['District of Columbia', 'DC'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Puerto Rico', 'PR'],
          ['Rhode Island', 'RI'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY']
        ]
    end

end

app/views/locations/_form.html.erb
<h2>Location Information</h2>
<%= form_with model:@location do |f| %>
<% if @location.errors.any? %>
        <div id="error_explanation">
            <h2>
            <%= pluralize(@location.errors.count, "error") %>
            prohibited this contract from being submitted:
            </h2>
            <ul>
            <% @location.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>


    <%= f.label :name %>
    <%= f.text_field :name %>
    <br><br>
    <%= f.label :utility %>
    <%= f.text_field :utility %>
    <br><br>
    <%= f.label :utility_load_zone %>
    <%= f.text_field :zone %><br>
    <br><br>
    <%= f.label :rate_type %>
    <%= f.text_field :meter_type %><br>
    <br><br>
    <%= f.label :state %>
    <%= f.select :state, us_states %>
    <br><br>
    <%= f.label :country %>
    <%= f.text_field :country %>
    <br><br>
    <%= f.label :Estimate_annual_capacity_in_killowatt_hours %>
    <%= f.text_field :annual_capacity %>
    <br><br>
    <%= f.label :status %>
    <%= f.select :status, ["proposed - contingent on finding PPA", "under construction, capacity available and looking for PPA", "online, capacity available and looking for PPA", "online - no additional capacity available"] %>
    <br><br>
    <%= f.submit %>
<% end %>

<br><br>
<a href="http://www.resonant.energy/mautilityloadzonemap" target="_blank">MA Load Zone Information</a>

app/views/locations/_list.html.erb
<body>
    <div class="container">
        <div class="row">

            <% @locations.each do |l| %>
                <div class="card">
                    <div class="card-header">
                        <h2><%= l.name %></h2><br>
                    </div>

                    <div class="card-body">

                        <p><% if l.annual_capacity-l.contracts.Accepted.sum(:capacity) >= 0 %>
                        <mark>There is an estimated excess supply of <%= l.annual_capacity-l.contracts.Accepted.sum(:capacity) %> kWh/year</mark><br>
                        <% end %></p><br>
                
                        <p><%= l.utility %>, <%= l.zone %>, rate type: <%= l.meter_type %><br>
                        <%= l.state %>, <%= l.country %></p><br>

                        <p>The Owner has marked this as: <%= l.status %><br>
                        Total Estimated Capacity: <%= l.annual_capacity %> kWh/year<br>
                        The Owner has <%= l.contracts.Accepted.sum(:capacity) %> kWh / year under contract at this location.<br></p><br>

                        <% if current_user == l.owner_id %>
                            <a href="<%= location_path(l.id) %>" class="btn">Edit Me</a>
                        <% else %>
                            <a href="<%= location_path(l.id) %>" class="btn">More Details</a>
                            
                        <% end %>
                        
                    </div>
                </div>   

            <% end %>     
        </div>
    </div>
</body>

app/views/locations/edit.html.erb
<%= render 'form' %>

app/views/locations/index.html.erb
<%= render 'list' %>

app/views/locations/mylocations.html.erb
<br>

<div class="center-font"><%= link_to "Please click here to create a new location", new_location_path %></div>

<%= render 'list' %>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/show.html.erb
<h2>Location Information</h2>
    <%= @location.name %> - Owners Name: <%= @location.owner.name %><br>
    Location created: <%= @location.created_at.strftime('%B %-d, %Y') %><br>
    <%= @location.utility %>, <%= @location.zone %>, rate type: <%= @location.meter_type %><br>
    <%= @location.state %>, <%= @location.country %><br>
    Total Estimated Capacity: <%= @location.annual_capacity %> kWh/year<br>

    The Owner has marked this as: <%= @location.status %><br>
<br><br>

Currently <%= @location.contracts.Accepted.sum(:capacity) %> kWh / year under contract at this location.<br>
Currently pending offers for <%= @location.contracts.Proposed.sum(:capacity) %> kWh / year on this location.<br><br>

<% if @location.contracts.length > 0 %>
This locations contracts are:<br>
    <% @location.contracts.each do |c| %>
        <%= c.capacity %> kWh / year, STATUS: <%=c.status%> - Ending: <%= c.end_date(c).strftime('%B %-d, %Y') %><br>
    <% end %>
<% end %>


<br><br>
<% if current_user != @location.owner_id %>
    <%= link_to "Submit PPA / Contract proposal to owner", new_contract_path %>
<% else %>
    <%= link_to "Click here to edit your locations information", edit_location_path(@location.id) %><br><br>
    <%= link_to "Click to see all contracts for this location", location_contracts_path(@location) %>
<% end %>