config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/locations/mylocations', to: 'locations#mylocations'
  get '/contracts/consumer', to: 'contracts#consumer'
  get '/contracts/owner', to: 'contracts#owner'

  root "application#aboutus"

  get '/users/email_confirmation', to: 'users#email_confirmation'

  resources :users
  resources :contracts
  resources :locations

  resources :locations, only: [:show] do
    # nested resource for contracts
    resources :contracts, only: [:new, :show, :index]
  end
#for new, look the nested routes up and plug into <%= link_to "add contract" new_catagory_item_path(c) %>
#

  get '/feedbacks/thankyou', to: 'feedbacks#thankyou'
  resources :feedbacks
  
  get '/aboutus', to: 'application#aboutus'
  
  get '/logout', to: 'sessions#logout'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#login_post'

  get '/signup', to: 'sessions#signup'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  #get ‘auth/failure’, to: redirect(‘/’)
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application',
    'https://fonts.googleapis.com/css2?family=Megrim&display=swap', 
    'https://fonts.googleapis.com/css2?family=Lato&family=Open+Sans&display=swap', 
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css',
    media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <header>
        <div class="logotext">
          <%= link_to "sol-search", locations_path %>
        </div>

      <div class="navbar">

      <% if current_user %>
    <div class="dropdown">
      <button class="dropbtn">options 

      </button>
      <div class="dropdown-content">
        <%= link_to "My Profile", user_path(current_user) %>
        <a href= "/locations/mylocations">My Solar</a>
        <%= link_to "Browse All Solar", locations_path %>
        <a href="/contracts/consumer">Purchase Contracts</a>
        <a href="/contracts/owner">Sale Contracts</a>
        <a class="active" href="/aboutus">About Us</a>
        <a href="/feedbacks/new">Feedback</a>
        <%= link_to "Sign Out", logout_path %><br>
      <% else %>
        <%= link_to "Click here to Sign Up", signup_path %>
        <%= link_to "Already have an account? Click here to Log In", login_path %>
        <br><br>
      <% end %>
      </div>
    </div>
    </div>



  <% flash.each do |type, msg| %>
      <div class="isa_info">
      <br>
        <i class="fa fa-info-circle" ><%= msg %></i>
      </div>
  <% end %>

  </header>

  <body>
    <%= yield %>
  </body>

</html>